### ISSUE TITLE
ssh key is not copied

### ISSUE THREAD

**Issue by andrey-utkin** [asarubbo/gentoo-stage4#4]
> If there is a file called id_rsa.pub in the same path where you are executing the stage4 script, this file will be copied as /root/.ssh/authorized_keys

This doesn't happen.

Seems it's because the script is `cd`ing to /tmp and later to `$MOUNTPOINT`.

**Comment by asarubbo** [comment]
Hello Andrey,

thanks for using it and thanks for the feedback. The fix is trivial, I didn't test it but at 'naked eye' it should work.

If you have any further issue please let me know.
